export const SELECT_PLAYER_FOR_EDITION = 'SELECT_PLAYER_FOR_EDITION'
export const UNSELECT_PLAYER_FOR_EDITION = 'UNSELECT_PLAYER_FOR_EDITION'
export const SELECT_PLAYER_FOR_DELETION = 'SELECT_PLAYER_FOR_DELETION'
export const UNSELECT_PLAYER_FOR_DELETION = 'UNSELECT_PLAYER_FOR_DELETION'
